import { useState, useEffect } from 'react';
import { fetchAuthSession } from 'aws-amplify/auth';
import productConfig from './product_config.json'; // Generated by Terraform

function DownloadDashboard() {
  const [loading, setLoading] = useState(true);
  const [ownedProducts, setOwnedProducts] = useState([]); // Array of IDs from DynamoDB
  const [error, setError] = useState('');
  const [downloadingId, setDownloadingId] = useState(null); // Tracks which item is fetching a link

  // 1. Sync the library on mount
  useEffect(() => {
    fetchUserLibrary();
  }, []);

  const fetchUserLibrary = async () => {
    try {
      const session = await fetchAuthSession();
      const token = session.tokens?.idToken?.toString();
      if (!token) throw new Error("Please log in to view your library.");

      // This endpoint returns a list of productIds bought by the user
      // Example response: ["cool-synth-v1", "retro-verb-v1"]
      const response = await fetch(`${import.meta.env.VITE_API_URL}/my-purchases`, {
        method: 'GET',
        headers: { 'Authorization': token }
      });

      if (response.ok) {
        const purchasedIds = await response.json();
        setOwnedProducts(purchasedIds);
      }
    } catch (err) {
      console.error("Library sync failed:", err);
      setError("Could not load your library.");
    } finally {
      setLoading(false);
    }
  };

  const handleBuy = async (productId) => {
    setLoading(true);
    try {
      const session = await fetchAuthSession();
      const token = session.tokens?.idToken?.toString();

      // Scalable: We pass the specific ID as a query param
      const response = await fetch(`${import.meta.env.VITE_API_URL}/checkout?id=${productId}`, {
        method: 'POST',
        headers: { 'Authorization': token }
      });

      const { checkoutUrl } = await response.json();
      window.location.href = checkoutUrl;
    } catch (err) {
      setError("Failed to start checkout. " + err);
      setLoading(false);
    }
  };

  const triggerDownload = async (productId) => {
    setDownloadingId(productId);
    try {
      const session = await fetchAuthSession();
      const token = session.tokens?.idToken?.toString();

      const response = await fetch(`${import.meta.env.VITE_API_URL}/download?productId=${productId}`, {
        method: 'GET',
        headers: { 'Authorization': token }
      });

      if (!response.ok) throw new Error("Verification failed.");

      const { downloadUrl } = await response.json();
      window.location.assign(downloadUrl);
    } catch (err) {
      setError(`Download failed for ${productId} ` + err);
    } finally {
      setDownloadingId(null);
    }
  };

  if (loading) return <div style={cardStyle}><p>Scanning your cloud library...</p></div>;

  return (
    <div style={cardStyle}>
      <h3 style={{ marginTop: 0 }}>🎵 My VST Library</h3>

      {productConfig.map((product) => {
        const isOwned = ownedProducts.includes(product.id);
        const isProcessing = downloadingId === product.id;

        return (
          <div key={product.id} style={itemRowStyle}>
            <div style={{ textAlign: 'left' }}>
              <div style={{ fontWeight: 'bold' }}>{product.name}</div>
              <div style={{ fontSize: '12px', color: '#666' }}>
                {isOwned ? "Owned ✅" : product.price}
              </div>
            </div>

            {isOwned ? (
              <button
                onClick={() => triggerDownload(product.id)}
                style={isProcessing ? disabledBtnStyle : downloadBtnStyle}
                disabled={isProcessing}
              >
                {isProcessing ? "Verifying..." : "Download"}
              </button>
            ) : (
              <button onClick={() => handleBuy(product.id)} style={buyBtnStyle}>
                Buy Now
              </button>
            )}
          </div>
        );
      })}

      {error && <p style={errorStyle}>⚠️ {error}</p>}
      {productConfig.length === 0 && <p>No products available in the shop.</p>}
    </div>
  );
}

// --- Styles (Added a disabled state) ---
const cardStyle = { margin: '20px auto', maxWidth: '450px', padding: '20px', backgroundColor: '#fff', borderRadius: '12px', boxShadow: '0 4px 12px rgba(0,0,0,0.1)', border: '1px solid #eee' };
const itemRowStyle = { display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#f9f9f9', padding: '15px', borderRadius: '8px', border: '1px solid #ececec', marginBottom: '10px' };
const downloadBtnStyle = { backgroundColor: '#ff9900', color: 'white', border: 'none', padding: '10px 20px', borderRadius: '6px', fontWeight: 'bold', cursor: 'pointer' };
const disabledBtnStyle = { ...downloadBtnStyle, backgroundColor: '#ccc', cursor: 'not-allowed' };
const buyBtnStyle = { backgroundColor: '#007bff', color: 'white', border: 'none', padding: '10px 20px', borderRadius: '6px', fontWeight: 'bold', cursor: 'pointer' };
const errorStyle = { color: '#d9534f', fontSize: '13px', marginTop: '15px', textAlign: 'center' };

export default DownloadDashboard;
